name: Build Godot Project

on:
  push: {
    branches: [main]
  }
  pull_request: {
    branches: [main]
  }

jobs:
  Godot:
    runs-on: ubuntu-latest
    environment: release
    strategy:
      matrix:
        platform: 
          - name: "windows"
            file: "2DSurvivorCourse.exe"
          - name: "linux"
            file: "2DSurvivorCourse"
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: ${{ matrix.platform.file }}
          preset: ${{ matrix.platform.name }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Latest - ${{ matrix.platform.name }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
